# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTest1:
    def setup_method(self):
        self.driver = webdriver.Firefox()
        # self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("http://localhost/addressbook/index.php")
        self.driver.set_window_size(550, 692)
        self.driver.find_element(By.NAME, "user").send_keys("admin")
        self.driver.find_element(By.NAME, "pass").send_keys("secret")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
        self.driver.find_element(By.LINK_TEXT, "groups").click()
        self.driver.find_element(By.NAME, "new").click()
        self.driver.find_element(By.NAME, "group_name").click()
        self.driver.find_element(By.NAME, "group_name").send_keys("wedewq")
        self.driver.find_element(By.NAME, "group_header").click()
        self.driver.find_element(By.NAME, "group_header").send_keys("wedwe")
        self.driver.find_element(By.NAME, "group_footer").click()
        self.driver.find_element(By.NAME, "group_footer").send_keys("wedewd")
        self.driver.find_element(By.NAME, "submit").click()
        # self.driver.find_element(By.LINK_TEXT, "home").click()
        self.driver.find_element(By.LINK_TEXT, "groups").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        # self.driver.find_element(By.CSS_SELECTOR, "html").click()
